### ISSUE TITLE
Request: Allow passing host to webpack dev server (support containers)

### ISSUE THREAD

**Issue by jdevera** [dvargas92495/roamjs-scripts#1]
I'm trying to start learning how roam extensions are built but I am trying to keep the dev environment in docker containers. I have managed to build and launch the dev server for my test extension [as per the instructions](https://developer.roamjs.com/roamjs-scripts/dev). However, because this is executed inside a docker container, and the host is [hardcoded to `127.0.0.1`](https://github.com/dvargas92495/roamjs-scripts/blob/d653e3f62424827b2cd284df605f76afa7e2faf8/src/index.ts#L250), I cannot connect to it from outside the container, even with the right port bindings in place.

For this scenario, I'd like to set the host to `0.0.0.0` as [instructed here](https://okteto.com/docs/tutorials/webpack/). Ideally without having to patch these dependencies.

**Would you consider adding a new command-line option or even env var to allow overriding the webpack dev server host? or even even a flag to set it to `0.0.0.0`?**

Thanks.

**Comment by dvargas92495** [comment]
command-line option or env sounds great to me! I'm a bit swamped this week so can't get to it until the end of the week, but PRs are welcome!
